### ISSUE TITLE
Stripe returns NOT_SUPPORTED_GATEWAY on checkoutPaymentCreate

### ISSUE THREAD

**Issue by madmonkeyworks** [saleor/apps#1022]
Hi there, 

We are getting NOT_SUPPORTED_GATEWAY error on checkoutPaymentCreate mutation. 
Our eshop charges customers after the order has been delivered. So we are creating payment intent, basically adding a payment card like below: 

```
mutation addPaymentCard {
  checkoutPaymentCreate(
    input: {gateway: "Stripe", token: "abcd"}
    id: "Q2hlY2tvdXQ6ZDJmOTg2M2YtMzc3Zi00YWQ2LTk4ZTgtZjI2ZmEzNGU4ZjVh"
  ) {
    errors {
      message
      code
      field
      variants
    }
    payment {
      id
    }
  }
}
```

Result is: 

```
{
  "data": {
    "checkoutPaymentCreate": {
      "errors": [
        {
          "message": "The gateway Stripe is not available for this checkout.",
          "code": "NOT_SUPPORTED_GATEWAY",
          "field": "gateway",
          "variants": null
        }
      ],
      "payment": null
    }
  },
  "extensions": {
    "cost": {
      "requestedQueryCost": 0,
      "maximumAvailable": 50000
    }
  }
}
```

Note that we tried **saleor.app.stripe** as gateway id as well, and the funny thing is that when we list the available payment gateways, Stripe gateway is present. 

Any idea what is wrong?

Our setup: 
- Saleor version 3.15.6
- Saleor cloud developer account
- Stripe app installed from Saleor marketplace
- Stripe configured with p_key and s_key (test mode)

**Comment by mmiszy** [comment]
It seems you're accidentally using the legacy stripe plugin instead of the app. `checkoutPaymentCreate` mutation should not be used here. Instead, follow this guide: https://docs.saleor.io/docs/3.x/developer/payments

**Comment by madmonkeyworks** [comment]
Hi @mmiszy, thanx for your response. Do we have any ways in saleor 3 to store payment methods?

**Comment by madmonkeyworks** [comment]
Could we have a session with any of you Saleor wizzards? Paid, of course. We are trying to get the Stripe working, but failing. The scenario we need is: first order, pay when order fulfilled.

**Comment by mmiszy** [comment]
Currently it's impossible to store and use payment methods.
We're working on it and you can track progress here: https://github.com/saleor/saleor/issues/12843

**Comment by lkostrowski** [comment]
>Could we have a session with any of you Saleor wizzards? Paid, of course

We are not running a paid support for non-Cloud users, but we are happy help by improving our products and resources, like docs.

If you want to share with us some non-public information, you can reach us at support@saleor.io

**Comment by madmonkeyworks** [comment]
Thank you @mmiszy and @lkostrowski. The [saleor/saleor#12843](https://github.com/saleor/saleor/issues/12843) is exactly what we're looking for. Great progress. Looking forward to the release. 
Thanks for your answers, I appreciate it very much.
