### ISSUE TITLE
CMS App - contentful resource ID is invalid

### ISSUE THREAD

**Issue by lkostrowski** [saleor/apps#1086]
Current implementation of Contentful is setting resource ID as a product variant ID in base64. That was initially implemented this way, because demo database of products in Saleor luckily have IDs that don't include special characters (like `==`). 

However, variant IDs eventually have characters that are forbidden in Contentful
https://www.contentful.com/developers/docs/references/content-management-api/#/introduction/authentication:~:text=developer%20center.-,Resource%20IDs,-When%20creating%20resources

Implementation of the Contetnful client must be changed. Possibilities:
- Rely on random ID from contentful
- ~decode variant ID: `UHJvZHVjdFZhcmlhbnQ6NDIz` -> atob -> `'ProductVariant:423'` -> replace `:` with `-`~

Don't decode since Saleor doesn't guarantee ID format

- [ ] Is it breaking change?

```[tasklist]
### Tasks
- [ ] https://github.com/saleor/apps/pull/1088
- [ ] Update docs
```

**Comment by lkostrowski** [comment]
https://github.com/saleor/saleor-docs/issues/1009

**Comment by jacobhallenborgprototyp** [comment]
I my humble opinion, it would be safer to let the target system in (this case Contentful) handle the ID generation itself. That way the App wouldn't have to worry about collisions or format details at all :)

**Comment by lkostrowski** [comment]
> I my humble opinion, it would be safer to let the target system in (this case Contentful) handle the ID generation itself. That way the App wouldn't have to worry about collisions or format details at all :)

Exactly. Especially that Saleor itself doesn't guarantee any format. It guarantees its unique, but format its internal detail of Saleor itself.

I will implement it using system id
