### ISSUE TITLE
Error: useAppBridge used outside of AppBridgeProvider - search

### ISSUE THREAD

**Issue by JannikZed** [saleor/apps#1095]
This is what I currently get when trying to open the configuration screen of the search app:

![Screenshot 2023-11-07 at 11 32 34](https://github.com/saleor/apps/assets/7526174/85a8fbe1-0c1f-4452-a0df-6fbe7742e296)
![Screenshot 2023-11-07 at 11 32 43](https://github.com/saleor/apps/assets/7526174/4fd84c07-0a86-4f33-ac48-1a06fcbc3e07)

**Comment by loick-yuno** [comment]
I have the same issue with the `Emails & Messages` app

**Comment by lkostrowski** [comment]
We are fixing this, here is the WIP PR

https://github.com/saleor/apps/pull/1096

**Comment by lkostrowski** [comment]
Hey, it should've been fixed in https://github.com/saleor/apps/pull/1099
