### ISSUE TITLE
ERROR - Emails & Messages - Application error: a client-side exception has occurred - useAppBridge used outside of AppBridgeProvider

### ISSUE THREAD

**Issue by loick-yuno** [saleor/apps#1097]
I'm getting an error since the new version while installing or editing the SendGrid provider on the `Emails & Messages` app, see screenshot: 
<img width="1979" alt="image" src="https://github.com/saleor/apps/assets/135331099/d32ce89c-d151-401c-9ce1-6ef05697bb13">

related to: https://github.com/saleor/apps/pull/1096 apparently

**Comment by lkostrowski** [comment]
Hey, it should've been fixed in https://github.com/saleor/apps/pull/1099
