### ISSUE TITLE
Add product price ranges to the variant document

### ISSUE THREAD

**Issue by krzysztofwolski** [saleor/apps#1104]
Currently, the variant document contains only its own prices. Due to constraints on how the Algolia is grouping the results, it's not possible to get a prices for all possible product variants. This is preventing us from showing price ranges ("$10-$20") in the search results.

Possible issues:
Investigate if subscription payload can contain price range for all of the changes, to avoid additional per channel queries.

Needed changes:
- Update the subscription to include product price range
- Update the `productAndVariantToAlgolia` function to add keys for product pricing (productPricing. start and productPricing.stop, both net and gross)

**Comment by lkostrowski** [comment]
When working on this, I found a functional bug: https://github.com/saleor/apps/issues/1108
