### ISSUE TITLE
Change the select to searchable select in tax code matcher

### ISSUE THREAD

**Issue by peelar** [saleor/apps#1130]
The tax code matcher displays a lot of tax codes for AvaTax. Currently, we use the `Select` element for it, which is a bad UX because it is not searchable. We should change it to Autocomplete or something similar

**Comment by lkostrowski** [comment]
https://github.com/saleor/macaw-ui/issues/452 rel

**Comment by peelar** [comment]
can be closed because https://github.com/saleor/apps/pull/1142
