### ISSUE TITLE
[feature] add handlebars-helpers to emails-and-messages

### ISSUE THREAD

**Issue by djkato** [saleor/apps#1370]
Handlebars is quite basic, and doesn't allow me to do string comparisons without helper functions. handlebars-helpers adds a lot of utility into the templating syntax, allowing me to do stuff like:

```jsx
<mj-text>
   The products you ordered have been prepared for pickup by 
   {{#if (eq order.deliveryMethod "Warehouse")}} 
       you at warehouse {{order.clickAndCollectPlaceOrWhateverItsCalled}} 
   {{else}} 
       courier {{order.ShippingMethodOrWhatever}}
   {{/if}}.
</mj-text>
```

I need this, because without it I can't do conditional text, meaning I have to write "ifs" and "ors" into the text itself, leading to possible confusion.
https://github.com/helpers/handlebars-helpers

**Comment by lkostrowski** [comment]
It was added to the SMTP app which has replaced the E&M app
