### ISSUE TITLE
Improve apps' contextual actions

### ISSUE THREAD

**Issue by lkostrowski** [saleor/apps#15]
This issue contains changes to the contextual app operations.

# Simplify apps list

![image](https://user-images.githubusercontent.com/9268745/208442276-08a2c98f-8d6d-4402-9d82-acf014805a95.png)

- Remove the "delete" button
- Remove the "enable/disable" button
- Add a button with the icon "cog" (settings-like) that should link to the "About app"

Reason: dangerous operations are not commonly used and should be more hidden

# Add "delete app" functionality to "About app" page

![Zrzut ekranu 2022-12-19 o 15 01 31](https://user-images.githubusercontent.com/9268745/208442759-42c2d7ca-1637-40ab-bbec-979bba7052c2.png)

Since "delete" will be removed from the list, it must be available. It should be moved to "About app" page

The actual design is not a priority because we need to refine this view, and redesign it to contain more features like debugging. So now let's ensure functionalities are available

**Comment by orzechdev** [comment]
First part of the implementation for this issue: https://github.com/saleor/saleor-dashboard/pull/2943

**Comment by karolm-saleor** [comment]
✓ QA Passed
