### ISSUE TITLE
Hide toolbar in AppPage

### ISSUE THREAD

**Issue by lkostrowski** [saleor/apps#17]
Apps have 2 toolbar
1. Main toolbar (will be removed in separate issue when navigation is moved to sidebar)
2. App Toolbar

The latter should be removed
![image](https://user-images.githubusercontent.com/9268745/208445713-68ecda65-67e5-44e8-a98b-22a959978bae.png)

1. "About" is no longer needed because "cog" in https://github.com/saleor/apps/issues/15 will link there
2. App name is not needed and it takes the space

In general apps will have better experience without scrolling inside it, so app will take 100vh screen size

**Comment by orzechdev** [comment]
100vh screen size doesn't guarantee that scrolling will not occur inside an app. Iframe can have content higher then 100vh, and to adjust the size of iframe container we would need some js which will automatically detect height in iframe and change it in dashboard container as well. Do we want to do have such an improvement or are the changes in https://github.com/saleor/saleor-dashboard/pull/2938 what we want for now?

**Comment by lkostrowski** [comment]
> 

@orzechdev its ok that app has internal scrolling, this is the point actually - to have a single scroll instead of 2 containers.

1. We need to remove first bar (about, back) to increase iframe height
2. We need to remove top navigation bar to increase iframe to 100vh
