### ISSUE TITLE
Improve CMS connections

### ISSUE THREAD

**Issue by lkostrowski** [saleor/apps#174]
1. Send both product ID and channel slug to CMS (when added, edited and removed)
2. Save CMS ID in product metadata (when added to to CMS and when removed)

**Comment by orzechdev** [comment]
I have completed this issue right away in the https://github.com/saleor/apps/issues/173.

CMS ids are added to the product variant metadata on product variant channel listing create operations and removed on product variant channel listing delete operations (via product variant webhooks). Variant channel slugs from its channel listings are also saved that way in CMSes right away (in JSON field). Mark as completed.
