### ISSUE TITLE
Improve channels configuration to be always up to date in Apps

### ISSUE THREAD

**Issue by lkostrowski** [saleor/apps#195]
In Invoices, Taxes apps:
1. Channles are fetched with the first app setup
2. Configuration is saved per channel (record<channelId, config)
3. In further usages, app fetches channels from config

# Current
If channel is removed or added, they are not specified in the config

# Expected
App should always fetch and display up to date channels (and other entities). Config should be applied on top of them

**Comment by krzysztofwolski** [comment]
Has been implemented in #236
