### ISSUE TITLE
Add "author" field to AppManifest

### ISSUE THREAD

**Issue by lkostrowski** [saleor/apps#208]
Optional (for now) field with `author` in AppManifest that will be displayed by dashboard

- [x] Update docs
- [x] Update Manifest in app-sdk
- [ ] Update apps

**Comment by przlada** [comment]
https://github.com/saleor/saleor/issues/12280

**Comment by lkostrowski** [comment]
@przlada plese link docs and add info about supported version

**Comment by przlada** [comment]
Manifest update in `app-sdk`: https://github.com/saleor/saleor-app-sdk/pull/218

**Comment by przlada** [comment]
Docs update: https://github.com/saleor/saleor-docs/pull/682
