### ISSUE TITLE
Loaders on apps view issue

### ISSUE THREAD

**Issue by wojteknowacki** [saleor/apps#250]
### Description of the issue
Dashboard and app loaders are displayed in different positions on the app detail view
…

### Steps to reproduce the problem

1. Go to the apps list view
2. Make sure **Invoices** app is installed
3. Open **Invoices** app

### Expected Result
Loader in one place until the app is loaded
…

### Actual Result
Loader is visible in the middle of the screen for 1s and then is gone with new loader poping out higher

https://user-images.githubusercontent.com/124166231/223659952-baf0e2c6-0d35-43ce-a89e-ae6c8fdca436.mov

### System information

Dashboard version:

`v3.12`

Core version:

`v?.?.?`

Operating system:

- [ ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Other

Browser:

- [ ] Safari
- [ ] Chrome
- [ ] Edge
- [ ] Other

**Comment by lkostrowski** [comment]
Done some time ago
