### ISSUE TITLE
QA: Taxes app testing

### ISSUE THREAD

**Issue by lkostrowski** [saleor/apps#268]
# Testing scenarios

## App installation

1. Go to App Store
2. Find the “Taxes” app
3. Click “install”, and then “Install app”

The app requires permissions: “handle taxes” and “manage orders”. I only tested it on an admin account. It would be great to check it on a regular account with these particular permissions.

## Channel configuration

In the “Channel name” list, you should only see channels configured to “use tax app” as a tax calculation method. You should see the “Channels not found” screen if no channel is configured**.** In that case, you must Configure a channel to “use tax app”. 

1. Go to Configuration → Taxes (or click the “Go to Tax Configuration” button), pick a channel, and in the “Select method of tax calculation” field, choose “Use tax app”. Hit “Save”.
2. Come back to the Tax App.
3. Check if the configured channel appears on the “Channel name” list in the application.

## Creating a provider

If a channel is configured to use the tax app, you should then see the “Tax providers not found” screen.

1. Click “Configure a tax provider” or go to the “Providers” tab.
2. Choose either “TaxJar” or “Avatax”.
    1. TaxJar
        1. Instance name - the name you give to the instance.
        2. API Key - the key you should obtain from your [TaxJar account](https://www.taxjar.com/)].
        4. Sandbox - set to `true`.
    2. Avatax
        1. Instance name - the name you give to the instance.
        2. Sandbox - `true`.
        3. Autocommit - `false`.
        5. Username, password, company name (Company) - should be obtained from the Avalara account. 
3. Click “Save”.

## Assigning a provider to a channel

1. After creating a provider, go to the “Channels” tab.
2. In the “Channel tax provider” field, choose the instance you created. If there is only one option, it will be pre-selected.
3. Fill in the “Ship from address” in the following format:
    1. Country: “US”
    2. Zip: US Postal Code, e.g. “92093”
    3. State: State code, e.g. “CA”
    4. City: e.g. “La Jolla”
    6. Street: e.g. “9500 Gilman Drive”

## Triggering the `ORDER_CALCULATE_TAXES` webhook

If you have a configured channel and assigned it a provider, you should:

1. Go to “Orders”, “Create order”
2. Choose the channel you configured to “use tax app“
3. Choose a customer.
    
The customer also must have a valid US address. Addresses from the sample database will not work. Here is an example:

> 123 Palm Grove Ln
> 90002 LOS ANGELES
> CA, United States of America
    
4. Add products.
5. Add shipping method.

The Tax App should calculate the “Taxes” value with or without the shipping method.
## Deleting a provider

1. Go to the “Providers” tab and click on the provider instance you want to delete.
2. Click the “Delete” button.

The provider should disappear from the list.

## Updating a provider

1. Choose a provider instance.
2. Update the instance name.
3. Click “Save”.

When you are creating a provider, you pass the valid credentials. When the Tax App is returning them, they are obfuscated (e.g. “**************3F11”). We had the following bug with it:

1. Create a provider with the credentials.
2. Try to update the provider (e.g. the instance name).
3. The app reads the obfuscated credentials from the form and updates the configuration with them. Then, when Saleor tried to calculate taxes using the Tax App, it was using the obfuscated credentials. The tax provider returned an error, but the user can’t see it (because there is no UI for for sync tax webhooks errors).

Right now, we detect if the “update” action is being performed with the obfuscated values. If so, then they are not being used to update the configuration.

To make sure it all works, it would be great to test the following scenario:

1. Create a TaxJar instance with API Key nr 1.
2. Create API Key nr 2 (regenerate or create a new account).
3. Update the TaxJar instance with API Key nr 2.

The App should then update the API Key.

**Comment by lkostrowski** [comment]
@peelar please provide testing scenarios 

cc @michalina-graczyk

**Comment by peelar** [comment]
@michalina-graczyk @lkostrowski https://www.notion.so/saleor/Tax-App-testing-scenarios-469ba7ec5d274e439c8c732d29761ea6?pvs=4

**Comment by michalina-graczyk** [comment]
Error: Abort fetching component for route: "/configuration"
1. Go to App Store
2. Find the “Taxes” app
3. Click “install”, and then “Install app”
Results: There is an error in the console but app is correctly installed
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/25908728/224980564-e95edf93-4c4e-4d28-b9dd-515e6b268c1b.png">

**Comment by michalina-graczyk** [comment]
Channel configuration
1. Go to Configuration -> taxes 
2. Set all chanells to `use flat rates`
3. Click 'save'
4. Go to apps -> Taxes app
5. You can see that channels Channel-PLN-2 and Channel USD are visible
6. Go back to configurations -> taxes
7. Find channel Channel-PLN-2 and Channel USD
Result: Method of tax calculation is changed to use tax app
[Untitled_ Mar 14, 2023 2_51 PM.webm](https://user-images.githubusercontent.com/25908728/225023016-50250970-129d-4a22-ac5a-cb2690924939.webm)

**Comment by michalina-graczyk** [comment]
Creating a provider
1. Click “Configure a tax provider” or go to the “Providers” tab.
2. Choose either “TaxJar” or “Avatax”.
    1. TaxJar
        1. Instance name - the name you give to the instance.
        2. API Key - the key you should obtain from your [[TaxJar account](https://www.taxjar.com/)](https://www.taxjar.com/). Please create your own, they allow for a free trial (mine just ended).
        3. Sandbox - set to `true`.
 Results:
<img width="1726" alt="Screenshot 2023-03-14 at 15 14 34" src="https://user-images.githubusercontent.com/25908728/225029283-52322788-2b90-4d72-9385-718343037684.png">

Request:
https://taxes.saleor.app/api/trpc/avataxConfiguration.get?batch=1&input={"0":{"id":"750231d5-246a-40cd-bbdb-7b04f18ed875"}}
Response:
```json [{"error":{"message":"[\n  {\n    \"code\": \"invalid_literal\",\n    \"expected\": \"avatax\",\n    \"path\": [\n      \"provider\"\n    ],\n    \"message\": \"Invalid literal value, expected \\\"avatax\\\"\"\n  },\n  {\n    \"code\": \"invalid_type\",\n    \"expected\": \"string\",\n    \"received\": \"undefined\",\n    \"path\": [\n      \"config\",\n      \"username\"\n    ],\n    \"message\": \"Required\"\n  },\n  {\n    \"code\": \"invalid_type\",\n    \"expected\": \"string\",\n    \"received\": \"undefined\",\n    \"path\": [\n      \"config\",\n      \"password\"\n    ],\n    \"message\": \"Required\"\n  },\n  {\n    \"code\": \"invalid_type\",\n    \"expected\": \"string\",\n    \"received\": \"undefined\",\n    \"path\": [\n      \"config\",\n      \"companyName\"\n    ],\n    \"message\": \"Required\"\n  },\n  {\n    \"code\": \"invalid_type\",\n    \"expected\": \"boolean\",\n    \"received\": \"undefined\",\n    \"path\": [\n      \"config\",\n      \"isAutocommit\"\n    ],\n    \"message\": \"Required\"\n  }\n]","code":-32603,"data":{"code":"INTERNAL_SERVER_ERROR","httpStatus":500,"path":"avataxConfiguration.get"}}}]```

**Comment by michalina-graczyk** [comment]
Creating a provider - Avatax
    1. Click “Configure a tax provider” or go to the “Providers” tab.
    1. Instance name - the name you give to the instance.
    2. Sandbox - `true`.
    3. Autocommit - `false`.
    4. Username, password, company name (Company) - should be obtained from the Avalara account.
    Result:
Request URL: https://taxes.saleor.app/api/trpc/providersConfiguration.getAll?batch=1&input=%7B%7D
Request Method: GET
Status Code: 500 
'''json [{"error":{"message":"[\n  {\n    \"code\": \"invalid_union\",\n    \"unionErrors\": [\n      {\n        \"issues\": [\n          {\n            \"code\": \"invalid_literal\",\n            \"expected\": \"taxjar\",\n            \"path\": [\n              2,\n              \"provider\"\n            ],\n            \"message\": \"Invalid literal value, expected \\\"taxjar\\\"\"\n          },\n          {\n            \"code\": \"invalid_type\",\n            \"expected\": \"object\",\n            \"received\": \"undefined\",\n            \"path\": [\n              2,\n              \"config\"\n            ],\n            \"message\": \"Required\"\n          }\n        ],\n        \"name\": \"ZodError\"\n      },\n      {\n        \"issues\": [\n          {\n            \"code\": \"invalid_literal\",\n            \"expected\": \"avatax\",\n            \"path\": [\n              2,\n              \"provider\"\n            ],\n            \"message\": \"Invalid literal value, expected \\\"avatax\\\"\"\n          },\n          {\n            \"code\": \"invalid_type\",\n            \"expected\": \"object\",\n            \"received\": \"undefined\",\n            \"path\": [\n              2,\n              \"config\"\n            ],\n            \"message\": \"Required\"\n          }\n        ],\n        \"name\": \"ZodError\"\n      }\n    ],\n    \"path\": [\n      2\n    ],\n    \"message\": \"Invalid input\"\n  }\n]","code":-32603,"data":{"code":"INTERNAL_SERVER_ERROR","httpStatus":500,"path":"providersConfiguration.getAll"}}}]'''

**Comment by szczecha** [comment]
Fetching channel:
Fetching channel, not all active channels with "taxCalculationStrategy": "TAX_APP", are on the tax app list

Steps:

**Comment by szczecha** [comment]
Taxes are not calculated 

Steps: 

1. Update channel to use tax strategy `tax_app`
2. Make sure that the Avalara plugin is disabled for this channel
3. Install tax app 
4. Update Avalara data in the Tax app in providers and channels. Save
5. Go to orders Create a new order in the channel and assign the existing customer and add a new valid address 
6. Select shipping method 

Result Taxes are not calculated 
Run query for
```
query App($id: ID!) {
  app(id: $id) {
    ...App
    __typename
  }
}

fragment App on App {
  id
  name
  created
  isActive
  permissions {
    code
    name
    __typename
  }
  manifestUrl
  webhooks {
    ...Webhook
    __typename
  }
  __typename
}

fragment Webhook on Webhook {
  id
  name
  isActive
  asyncEvents {
    name
    eventType
  }
  syncEvents {
    name
    eventType
  }
  targetUrl
  subscriptionQuery
  eventDeliveries(last: 1) {
    edges {
      node {
        status
        eventType
        createdAt
        attempts(last: 5) {
          edges {
            node {
              duration
              status
              response
              responseStatusCode
              responseHeaders
              requestHeaders
            }
          }
        }
        payload
      }
    }
  }
  __typename
}
```

Response for wehbook eventDeliveries: 
```
"node": {
                                    "status": "FAILED",
                                    "eventType": "ORDER_CALCULATE_TAXES",
                                    "createdAt": "2023-03-20T10:57:06.617276+00:00",
                                    "attempts": {
                                        "edges": [
                                            {
                                                "node": {
                                                    "duration": 0.0,
                                                    "status": "FAILED",
                                                    "response": "HTTPSConnectionPool(host='taxes.saleor.app', port=443): Read timed out. (read timeout=20)",
                                                    "responseStatusCode": null,
      
```

**Comment by szczecha** [comment]
Error. No provider available
Installed app 1.1.0

1. Install app
2. Add providers taxJar and Avalara 
3. Try to update instance name for Avalara 
4. Save 
5. Refresh the page 

Result: Internal Server error "path": "providersConfiguration.getAll"
Request URL: https://taxes.staging.saleor.app/api/trpc/providersConfiguration.getAll?batch=1&input=%7B%7D
```
[
    {
        "error": {
            "message": "[\n  {\n    \"code\": \"invalid_union\",\n    \"unionErrors\": [\n      {\n        \"issues\": [\n          {\n            \"code\": \"invalid_literal\",\n            \"expected\": \"taxjar\",\n            \"path\": [\n              1,\n              \"provider\"\n            ],\n            \"message\": \"Invalid literal value, expected \\\"taxjar\\\"\"\n          },\n          {\n            \"code\": \"invalid_type\",\n            \"expected\": \"object\",\n            \"received\": \"undefined\",\n            \"path\": [\n              1,\n              \"config\"\n            ],\n            \"message\": \"Required\"\n          }\n        ],\n        \"name\": \"ZodError\"\n      },\n      {\n        \"issues\": [\n          {\n            \"code\": \"invalid_literal\",\n            \"expected\": \"avatax\",\n            \"path\": [\n              1,\n              \"provider\"\n            ],\n            \"message\": \"Invalid literal value, expected \\\"avatax\\\"\"\n          },\n          {\n            \"code\": \"invalid_type\",\n            \"expected\": \"object\",\n            \"received\": \"undefined\",\n            \"path\": [\n              1,\n              \"config\"\n            ],\n            \"message\": \"Required\"\n          }\n        ],\n        \"name\": \"ZodError\"\n      }\n    ],\n    \"path\": [\n      1\n    ],\n    \"message\": \"Invalid input\"\n  }\n]",
            "code": -32603,
            "data": {
                "code": "INTERNAL_SERVER_ERROR",
                "httpStatus": 500,
                "path": "providersConfiguration.getAll"
            }
        }
    }
]
```

https://user-images.githubusercontent.com/30683248/226843051-d6ec1bdd-0c02-4fd0-9903-529973784859.mov

**Comment by szczecha** [comment]
2 webhooks with the same subscription query are created 
Installed app 1.1.0

1. Install app
2. Update Avatax provider data
3. Update channel address 

```
            "webhooks": [
                {
                    "id": "V2ViaG9vazo2OTM=",
                    "name": "OrderCalculateTaxes",
                    "isActive": true,
                    "asyncEvents": [],
                    "syncEvents": [
                        {
                            "name": "Order calculate taxes",
                            "eventType": "ORDER_CALCULATE_TAXES"
                        }
                    ],
                    "targetUrl": "https://taxes.staging.saleor.app/api/webhooks/order-calculate-taxes",
                    "subscriptionQuery": "subscription CalculateTaxes { event { ...CalculateTaxesEvent }}fragment CalculateTaxesEvent on Event { __typename ... on CalculateTaxes { taxBase { ...TaxBase } }}fragment TaxBase on TaxableObject { currency channel { slug } discounts { ...TaxDiscount } address { streetAddress1 streetAddress2 city country { code } countryArea postalCode } shippingPrice { amount } lines { ...TaxBaseLine }}fragment TaxDiscount on TaxableObjectDiscount { name amount { amount }}fragment TaxBaseLine on TaxableObjectLine { chargeTaxes sourceLine { __typename ... on CheckoutLine { id productVariant: variant { id product { metafield(key: \"taxjar_tax_code\") productType { metafield(key: \"taxjar_tax_code\") } } } } ... on OrderLine { id variant { id product { metafield(key: \"taxjar_tax_code\") productType { metafield(key: \"taxjar_tax_code\") } } } } } quantity unitPrice { amount } totalPrice { amount }}",
                    "eventDeliveries": {
                        "edges": []
                    },
                    "__typename": "Webhook"
                },
                {
                    "id": "V2ViaG9vazo2OTQ=",
                    "name": "CheckoutCalculateTaxes",
                    "isActive": true,
                    "asyncEvents": [],
                    "syncEvents": [
                        {
                            "name": "Checkout calculate taxes",
                            "eventType": "CHECKOUT_CALCULATE_TAXES"
                        }
                    ],
                    "targetUrl": "https://taxes.staging.saleor.app/api/webhooks/checkout-calculate-taxes",
                    "subscriptionQuery": "subscription CalculateTaxes { event { ...CalculateTaxesEvent }}fragment CalculateTaxesEvent on Event { __typename ... on CalculateTaxes { taxBase { ...TaxBase } }}fragment TaxBase on TaxableObject { currency channel { slug } discounts { ...TaxDiscount } address { streetAddress1 streetAddress2 city country { code } countryArea postalCode } shippingPrice { amount } lines { ...TaxBaseLine }}fragment TaxDiscount on TaxableObjectDiscount { name amount { amount }}fragment TaxBaseLine on TaxableObjectLine { chargeTaxes sourceLine { __typename ... on CheckoutLine { id productVariant: variant { id product { metafield(key: \"taxjar_tax_code\") productType { metafield(key: \"taxjar_tax_code\") } } } } ... on OrderLine { id variant { id product { metafield(key: \"taxjar_tax_code\") productType { metafield(key: \"taxjar_tax_code\") } } } } } quantity unitPrice { amount } totalPrice { amount }}",
                    "eventDeliveries": {
                        "edges": []
                    },
                    "__typename": "Webhook"
                }
            ],
```

**Comment by peelar** [comment]
> Creating a provider - TaxJar
> 
> 1. Click “Configure a tax provider” or go to the “Providers” tab.
> 2. Choose either “TaxJar”
>    
>    1. TaxJar
>       
>       1. Instance name - the name you give to the instance.
>       2. API Key - the key you should obtain from your [[TaxJar account](https://www.taxjar.com/)](https://www.taxjar.com/). Please create your own, they allow for a free trial (mine just ended).
>       3. Sandbox - set to `true`.
>          Results:
> 
> <img alt="Screenshot 2023-03-14 at 15 14 34" width="1726" src="https://user-images.githubusercontent.com/25908728/225029283-52322788-2b90-4d72-9385-718343037684.png">
> 
> Request: [https://taxes.saleor.app/api/trpc/avataxConfiguration.get?batch=1&input={"0":{"id":"750231d5-246a-40cd-bbdb-7b04f18ed875"}}](https://taxes.saleor.app/api/trpc/avataxConfiguration.get?batch=1&input=%7B%220%22:%7B%22id%22:%22750231d5-246a-40cd-bbdb-7b04f18ed875%22%7D%7D) Response:
> 
> ```
> [
>     {
>         "error": {
>             "message": "[\n  {\n    \"code\": \"invalid_literal\",\n    \"expected\": \"avatax\",\n    \"path\": [\n      \"provider\"\n    ],\n    \"message\": \"Invalid literal value, expected \\\"avatax\\\"\"\n  },\n  {\n    \"code\": \"invalid_type\",\n    \"expected\": \"string\",\n    \"received\": \"undefined\",\n    \"path\": [\n      \"config\",\n      \"username\"\n    ],\n    \"message\": \"Required\"\n  },\n  {\n    \"code\": \"invalid_type\",\n    \"expected\": \"string\",\n    \"received\": \"undefined\",\n    \"path\": [\n      \"config\",\n      \"password\"\n    ],\n    \"message\": \"Required\"\n  },\n  {\n    \"code\": \"invalid_type\",\n    \"expected\": \"string\",\n    \"received\": \"undefined\",\n    \"path\": [\n      \"config\",\n      \"companyName\"\n    ],\n    \"message\": \"Required\"\n  },\n  {\n    \"code\": \"invalid_type\",\n    \"expected\": \"boolean\",\n    \"received\": \"undefined\",\n    \"path\": [\n      \"config\",\n      \"isAutocommit\"\n    ],\n    \"message\": \"Required\"\n  }\n]",
>             "code": -32603,
>             "data": {
>                 "code": "INTERNAL_SERVER_ERROR",
>                 "httpStatus": 500,
>                 "path": "avataxConfiguration.get"
>             }
>         }
>     }
> ]
> ```

@michalina-graczyk Is there anything specific about the values you provided?

**Comment by peelar** [comment]
> Fetching channels: not all active channels with "taxCalculationStrategy": "TAX_APP", are available on the tax app list

@szczecha When changing the tax configuration method to "tax app", are you sure you hit the "save" button? The UX there is quite misleading. If you:

1. Go to Channel 1, change the configuration
2. Go to Channel 2, change the configuration. Hit the "Save" button

the Channel 1 configuration will not be updated.

**Comment by peelar** [comment]
> 2 webhooks with the same subscription query are created

@szczecha This is not a bug. We have two webhook events, but one subscription query for them.

**Comment by szczecha** [comment]
> > Missing order event "Order sent to Avatax."
> 
> @szczecha Thanks, this is a missing feature that will be done this sprint.

https://user-images.githubusercontent.com/30683248/227899827-f752edc3-91be-478c-9b5c-5394c14b2df1.mov

**Comment by peelar** [comment]
@szczecha Thanks! That's very helpful, I will investigate.

**Comment by peelar** [comment]
Created the following issues:
- https://github.com/saleor/apps/issues/331
- https://github.com/saleor/apps/issues/332
- https://github.com/saleor/apps/issues/333

**Comment by peelar** [comment]
Here is a more detailed summary of my follow-up:

> @michalina-graczyk Error: Abort fetching component for route: "/configuration"
Fixed ✅.

> @michalina-graczyk Channel configuration
Reported to Dashboard.
 
> @michalina-graczyk Creating a provider - TaxJar
Fixed ✅.

> @michalina-graczyk Creating a provider - Avatax
Fixed ✅.

> @szczecha Fetching channels: not all active channels with "taxCalculationStrategy": "TAX_APP", are available on the tax app list
Need to be investigated 👀. Can you provide more details? Does it show up after a while? Is it always happening?

> @szczecha Taxes are not calculated
Fixed ✅.

> @szczecha Unable to setup taxJar
Fixed ✅.

> @szczecha Error. No provider available
Fixed ✅.

> @szczecha 2 webhooks with the same subscription query are created
Not a bug.

> @szczecha Missing order event "Order sent to Avatax."
Not a bug, but a missing feature. I am working on it here: https://github.com/saleor/apps/pull/355.
