### ISSUE TITLE
Add missing `app` field in app extension token

### ISSUE THREAD

**Issue by lkostrowski** [saleor/apps#308]
Related issue in core https://github.com/saleor/saleor/issues/12335

**Comment by lkostrowski** [comment]
@orzechdev please re-test it with the previous setup if extensions work

**Comment by orzechdev** [comment]
I see it is working correctly, app is displayed, everything works, every request, query, no connection errors, etc.
<img width="1917" alt="Screenshot 2023-03-27 at 11 01 12" src="https://user-images.githubusercontent.com/9825562/227894487-9a200f49-7c20-4b83-a6fb-92aecd242021.png">

**Comment by lkostrowski** [comment]
Great, closing
