### ISSUE TITLE
Improve webhook configuration list

### ISSUE THREAD

**Issue by lkostrowski** [saleor/apps#342]
- Should be "disabled" by default
- Should be disabled if not configured/no template assigned
- Show template name on the list (so you don't have to go inside to preview it)

**Comment by krzysztofwolski** [comment]
<img width="1787" alt="image" src="https://github.com/saleor/apps/assets/5188636/8aad9875-0eff-41f4-9a09-a56e71f53d09">

Implemented. Webhooks are created after the event is configured
