### ISSUE TITLE
Explore NOTFIY_USER event 

### ISSUE THREAD

**Issue by lkostrowski** [saleor/apps#365]
https://docs.saleor.io/docs/3.x/developer/extending/apps/sample-webhook-payloads#notify

1. Verify which of them are used in plugin
2. Verify which of them are missing in App to achieve parity with plugin
3. Create subtasks to implement each event in the app

Lets try to use them temporary before subscription events are created

**Comment by krzysztofwolski** [comment]
@lkostrowski
Was able to receive NOTIFY_EVENTS. It seems we'll be able to use it for the missing events (got an account registration event that was missing in the subscription implementation).
I'll proceed with the implementation

**Comment by lkostrowski** [comment]
@krzysztofwolski can you please create tickets for each missing event, so we can track them all independently?

**Comment by lkostrowski** [comment]
Customer events will be created in https://github.com/saleor/apps/issues/391
