### ISSUE TITLE
QA: CMS App - bulk products upload

### ISSUE THREAD

**Issue by orzechdev** [saleor/apps#372]

**Comment by lkostrowski** [comment]
Hey @saleor/qa , Dawid added new feature to the app, available on staging (cms.staging.saleor.app/api/manifest) with scenarios in this issue. I've added it to "backlog" in the QA board. Please let us know if there is anything more to describe

**Comment by michalina-graczyk** [comment]
Ad 1.
1. Install app
2. Configure the Contentfull provider
3. Click Save
4. Select a channel and set contentful provider as a active
5. Click "Sync" button
Results on the screenshot:

<img width="931" alt="image" src="https://user-images.githubusercontent.com/25908728/232455365-fdd2897f-45bd-46e0-a84b-71ed7a3138ed.png">

**Comment by michalina-graczyk** [comment]
Sync for Datmo CMS
1. Install app https://saleor-app-cms-git-cms-qa-fixes-saleorcommerce.vercel.app/api/manifest
2. Configure the DatoCMS provider
3. Click Save
4. Select a channel and set contentful provider as a active
5. Click "Sync" button
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/25908728/232470564-ea3e2294-f144-4bfb-befa-9278d22c7cdb.png">
`{"success":false,"data":{"createdCMSIds":[],"deletedCMSIds":[]},"error":"Error creating batch items."}`

**Comment by orzechdev** [comment]
@michalina-graczyk I'll make error handling more friendly to user, although in case of DatoCMS, the configuration you setup looks wrong. Did you set proper Item Type ID and proper API Token?
<img width="420" alt="Screenshot 2023-04-18 at 09 50 48" src="https://user-images.githubusercontent.com/9825562/232709661-4667b904-c501-4cbb-9746-455339a39d64.png">

**Comment by michalina-graczyk** [comment]
@orzechdev I changed the config for the proper one but I am still getting a 500 
![image](https://user-images.githubusercontent.com/25908728/232725999-647af832-b160-4cb6-a12d-36c6fca50f20.png)

<img width="952" alt="image" src="https://user-images.githubusercontent.com/25908728/232725906-2bb59f2a-9619-4848-9bac-bd99d828de3f.png">

**Comment by orzechdev** [comment]
@michalina-graczyk  Error after syncing products will be fixed in https://github.com/saleor/apps/issues/416
