### ISSUE TITLE
how to add an app to the dashboard?

### ISSUE THREAD

**Issue by devdjangoreact** [saleor/apps#441]
![Capture](https://user-images.githubusercontent.com/112485810/235776860-1fdc3149-291a-436d-a0c7-f12487b384a6.PNG)
it is ranning on docker in vps

**Comment by devdjangoreact** [comment]
it is ranning on docker in vps

**Comment by lkostrowski** [comment]
Hey @devdjangoreact 

App Store apps are disabled in self-hosted Saleor on purpose. Apps hosted in Saleor infrastructure can be only installed in Saleor Cloud instances

For self-hosted Saleor like yours, you need to host the app by yourself 

Here is a simple doc explaining how to fork the repository 
https://docs.saleor.io/docs/3.x/developer/app-store/forking

Apps are built on Next.js and should be easily deployable to Vercel
