### ISSUE TITLE
Typo in the Invoices App 

### ISSUE THREAD

**Issue by 2can** [saleor/apps#446]
![image](https://user-images.githubusercontent.com/779644/237024151-aa19e062-ef2c-4f23-9643-23b5c758731e.png)

https://github.com/saleor/apps/blob/main/apps/invoices/src/modules/app-configuration/ui/channels-configuration.tsx#L102

**Comment by lkostrowski** [comment]
Thanks, the app is going to be soon completely redesigned, its already waiting for a merge
https://github.com/saleor/apps/pull/445
