### ISSUE TITLE
CMS app Providers & Channels not loading

### ISSUE THREAD

**Issue by simon-online** [saleor/apps#513]
Ok so I have a self hosted working deployment of Saleor on GCP Kubernetes and I have the Dashboard and Saleor CMS app successfully deployed on Vercel on their own separate sub-domains.

I have been able to successfully install the Saleor CMS app from the Dashboard like so:

![Screen Shot 2023-05-27 at 1 30 47 am](https://github.com/saleor/apps/assets/10040020/26da0052-1263-415e-bcc2-c77347c4f891)

However when I click on the CMS app and go to configure Providers or Channels it doesn't load and just stays as follows:

![Screen Shot 2023-05-27 at 1 40 29 am](https://github.com/saleor/apps/assets/10040020/bc3d43d9-1cc9-4009-89ce-bb81ef92cb43)
![Screen Shot 2023-05-27 at 1 40 54 am](https://github.com/saleor/apps/assets/10040020/109e8125-f16d-482c-a6f2-475060d1c6ca)

When I view the network requests in Chrome Dev Tools I can see that the GET request to /api/provider-instances on the CMS app has failed with a 401 Unauthorized status code. I wasn't sure why the request was getting this error status since I was able to successfully install the app.

I also tried to update the Saleor deployment ALLOWED_CLIENT_HOSTS setting to allow all frontend sub-domains and .vercel.app sub-domains and tried it with DEBUG turned on and re-installed the CMS app but I still get the 401 Unauthorized status code.

My CMS app deployment is configured to use the upstash APL with a Vercel KV database as detailed [here](https://github.com/saleor/apps/issues/69#issuecomment-1563732609).

I tried this with:
dashboard v3.13.3
core v3.13.16
CMS app v1.5.1

Any idea what I can do to troubleshoot / resolve this?

**Comment by simon-online** [comment]
Ok, so the reason I was getting the 401 Unauthorized status code was because it was getting the "APL didn't found auth data for API URL" in the saleor-app-sdk processSaleorProtectedHandler() method.
https://github.com/saleor/saleor-app-sdk/blob/989810fbc659f3057756b96672ed8c46c6707445/src/handlers/next/process-protected-handler.ts#L82

This was the result of `saleorApiUrl` in APL `authData` getting set to the `http://` protocol when the Saleor API was running on `https://`. So when the CMS app tried to read the auth data the API URL didn't match `saleorApiUrl` in APL `authData` because of the protocol mismatch and threw an error.

The reason this was happening was because I hadn't configured `ENABLE_SSL=True` in the Saleor API environment variable settings. Once that was configured and working then the issue was resolved.

**Comment by lkostrowski** [comment]
Hey @simon-online , letting you know that I have rebuilt this app. You can check `apps/cms-v2`

**Comment by simon-online** [comment]
@lkostrowski Ok great. I have successfully deployed v2.1.1 on Vercel and it looks to be working better than the older version.

I was able to use Initial sync to sync 1,360 product variants to the Strapi CMS which isn't the full product catalogue but is certainly a lot more than the older version.

Will hopefully get the full product catalogue synced when I re-import all the products to Saleor.

**Comment by lkostrowski** [comment]
@simon-online CMSes seem not to provide a bulk APIs so the app has to import product one by one. Its not transactional but I don't think we can do much about it
