### ISSUE TITLE
Error running CMS app locally in development mode

### ISSUE THREAD

**Issue by simon-online** [saleor/apps#549]
I am running the CMS app locally in development mode and using ngrok to test it against our own deployment of Saleor. The CMS app installs ok in the dashboard however when I click on the CMS app and go to configure Providers or Channels, the following error occurs:
```
Unhandled Runtime Error
Error: useAppBridge used outside of AppBridgeProvider
```
```
../packages/shared/src/use-dashboard-notification.ts (5:36) @ useDashboardNotification
  4 | export const useDashboardNotification = () => {
> 5 | const { appBridge } = useAppBridge();
```

![Screen Shot 2023-06-10 at 7 05 09 am](https://github.com/saleor/apps/assets/10040020/fc338825-9185-4170-abae-5c7f178e3327)

I'm not quite sure what the proper steps are to set up the dev environment but this is what I'm doing:
```
git clone https://github.com/saleor/apps.git
cd apps/apps/cms
pnpm install
pnpm run dev
ngrok http 3000
```

It may not have anything to do with it but I am getting a warning:
warn - Attempted to load @next/swc-darwin-x64, but an error occurred (load command 0x80000034 is unknown)

The reason I'm doing this is to try to troubleshoot this other issue:
https://github.com/saleor/apps/issues/513

dashboard v3.13.3
core v3.13.16
CMS app v1.5.3

**Comment by lkostrowski** [comment]
Hey @simon-online please try to run `pnpm build && pnpm start` in app's directory and verify if the production build works. It will run server you can tunnel just like the dev server

**Comment by lkostrowski** [comment]
@simon-online I checked locally and I dont have this problem on latest main. Can you please verify your pnpm version? Root package sets `"packageManager": "pnpm@8.2.0",`

I know that newer pnpm versions may resolve dependencies differently so the issue may be there

Also please check if your pnpm-lock doesn't  differ after installation on your machine

**Comment by simon-online** [comment]
@lkostrowski Yes, this was the issue thanks. I was running pnpm v7.1.7. After upgrading to v8.2.0 it started working.

How can I view the debug messages when I run the app with `pnpm dev`? For example this debug call in saleor-app-sdk:
https://github.com/saleor/saleor-app-sdk/blob/989810fbc659f3057756b96672ed8c46c6707445/src/handlers/next/process-protected-handler.ts#L56

I'm able to connect to the node debugger that is started with Chrome but I don't see anything logging in the node debugger console. I have all debug levels set including Verbose.

I believe this is where the [401 Unauthorised issue](https://github.com/saleor/apps/issues/513) that I'm having is occurring.

**Comment by lkostrowski** [comment]
set `APP_LOG_LEVEL=trace` env to log app logs, I can't promise if you find there everything, the CMS app needs some improvements 

to enable debug logs for app-sdk - https://github.com/saleor/saleor-app-sdk/blob/main/docs/debugging.md

**Comment by simon-online** [comment]
@lkostrowski Thanks for your help. I was able to enable the app-sdk debugging which helped me resolve the issue.
