### ISSUE TITLE
QA: Taxes App redesign

### ISSUE THREAD

**Issue by peelar** [saleor/apps#554]
# QA: Taxes App redesign

## Context

We redesigned the Taxes App. Besides revamping the UI, the only change in terms of functionality is the addition of address validation (mentioned in 1.1).

You can reference the previous [QA PR](https://github.com/saleor/apps/issues/268).

### Installation

1. Go to App Store
2. Find the “Taxes” app
3. Click “install”, and then “Install App”

The app requires permissions: “handle taxes” and “manage orders”. I only tested it on an admin account. It would be great to check it on a regular account with these particular permissions.

#### 1. "Tax providers" view

![image](https://github.com/saleor/apps/assets/44495184/42766af7-8dea-4856-9122-71daea2a5f26)

##### 1.1 Creating a provider

If you haven't created a provider already, you should see the "Add first provider" button.

1. Click on the "Add first provider" button.
2. Choose a provider from the list. Test the next steps for all the providers (Avatax, TaxJar).
3. The provider form consists of 3-4 sections:
- Header - contains the required configuration name field.
- Credentials - contains the credentials needed to authenticate the configuration. The values are validated asynchronously, so you should see an error if they are incorrect. Also, after you submit the form, the values you provided here should be obfuscated (characters should be replaced with "****"). **Please test the validation and the obfuscation.**
- Address - contains the address the customer wants to use to calculate the taxes. The address is validated asynchronously, so you should see an error if it is incorrect. **Please test the validation.**
- Tax codes (only in Avatax) - contains the field to map the shipping tax code to a custom value.

###### Edge-cases ⚠️:
- In Avatax, you must pass the valid combination of credentials + sandbox mode toggle value.

  So if we assume that the following configuration is correct:
  - username: "qwerty"
  - password: "topsecret123"
  - isSandbox: `false`

  the following is incorrect:
  - username: "qwerty"
  - password: "topsecret123"
  - isSandbox: `true`
  
  In TaxJar, it doesn't matter.
  
  **Please test the logic.**
  
- If you want to ensure you used a valid address, I suggest copying some from [Sales Tax API Demo from TaxJar](https://developers.taxjar.com/demo/).

4. Click "Save".

##### 1.2 Viewing the providers

If you successfully created a provider, you should see it in a table:

![image](https://github.com/saleor/apps/assets/44495184/f4229b86-66e3-4513-9d38-118ba57e54e8)

1. Make sure all the created providers display in the table.

##### 1.3 Editing a provider

1. Click on an item's "Edit" in the providers' table.
2. Make sure all the data is loaded correctly.
3. Edit some fields and make sure you can submit the form.

###### Edge-cases ⚠️:

After submitting the credentials, they get obfuscated (all but the last 4 characters are replaced with "*"). There was an issue in the past with submitting the obfuscated values to update the provider (so trying to set the password to: `********t123`).

If the values are obfuscated, they shouldn't be used to update the provider. If the user updates the values in the UI, they should be considered.

1. Please test if the obfuscation works as described above.

##### 1.4 Deleting a provider
1. Click on an item's "Edit" in the providers' table.
2. Click the "delete provider" button. 
3. Make sure you are redirected to the home screen, and the provider doesn't display in the providers' table or the providers select in the "available channels view".

#### 2. "Available channels" view

If you configured the channel to use the tax app as the tax calculation method, you should see it in the table:

![image](https://github.com/saleor/apps/assets/44495184/b2dac805-2ec0-4db1-a37b-e657a325e5e4)

##### 2.1 Assigning a provider
1. In the "Provider" select next to the channel slug, you should see a list of providers defined in the table above ("tax providers").
2. Please assign/unassign a channel.

#### 3.1 Triggering the `ORDER_CALCULATE_TAXES` webhook

If you have a configured channel and assigned it a provider, you should:

1. Go to “Orders”, “Create order”
2. Choose the channel you configured to “use tax app“
3. Choose a customer.
    
The customer also must have a valid US address. Addresses from the sample database will not work. Here is an example:

> 123 Palm Grove Ln
> 90002 LOS ANGELES
> CA, United States of America
    
4. Add products.
5. Add shipping method.

Executing these instructions should result in using the configured tax provider to calculate the taxes. 

---

@saleor/qa If you have any questions, please shoot them my way. Kudos to you in advance for the brilliant work you are doing 🙇.

**Comment by yellowee** [comment]
Incorrect error message upon an attempt to create/update TaxJar provider with sandbox enabled:
`The provided address is invalid. Please visit https://support.taxjar.com/article/659-address-validation to learn about address formatting.`

![Screenshot 2023-06-15 at 14 34 54](https://github.com/saleor/apps/assets/24992893/893ea121-dabd-4920-bcb1-38cd09d4c22e)


This error occurs regardless if I provide Live Token or Sandbox Token.

```
POST 500 https://taxes.staging.saleor.app/api/trpc/taxJarConnection.update?batch=1
POST 500 https://taxes.staging.saleor.app/api/trpc/taxJarConnection.create?batch=1
```

Make sure to provide **valid address** and `isSandbox: true`
sample valid address:
`address: {country: "US", zip: "92614", state: "CA", city: "Irvine", street: "2000 Main st"}`

Please note: Disabling `Use sandbox mode` radio button makes it possible to create a new TaxJar provider.

**Comment by yellowee** [comment]
Unable to update the provider data:
1. Edit an existing provider.
2. Update the provider name/provide a new valid address.
3. Save.
Expected result: The provider is updated, new data are displayed straight away and when page is reloaded/entered again.
Actual result: There is a snackbar success message and the data shown are the one which were provided during update but they turn back to the original ones upon the page reload (the data remain the same).



- Issue occurs on TaxJar and Avatax

`curl 'https://taxes.staging.saleor.app/api/trpc/taxJarConnection.update?batch=1' \
  -H 'authority: taxes.staging.saleor.app' \
  -H 'accept: */*' \
  -H 'accept-language: en-GB,en;q=0.9' \
  -H 'authorization-bearer: eyJhbGciOiJSUzI1NiIsImtpZCI6IjEiLCJ0eXAiOiJKV1QifQ.eyJpYXQiOjE2ODY4MzE4NDIsIm93bmVyIjoic2FsZW9yIiwiaXNzIjoiaHR0cHM6Ly9tYXN0ZXIuc3RhZ2luZy5zYWxlb3IuY2xvdWQvZ3JhcGhxbC8iLCJleHAiOjE2ODY5MTgyNDIsInRva2VuIjoiTTJpckZtelZBU1IzIiwiZW1haWwiOiJ0ZXN0ZXJzK2Rhc2hib2FyZEBzYWxlb3IuaW8iLCJ0eXBlIjoidGhpcmRwYXJ0eSIsInVzZXJfaWQiOiJWWE5sY2pveE1ETXoiLCJpc19zdGFmZiI6dHJ1ZSwiYXBwIjoiUVhCd09qZzMiLCJwZXJtaXNzaW9ucyI6WyJIQU5ETEVfVEFYRVMiLCJNQU5BR0VfT1JERVJTIl0sInVzZXJfcGVybWlzc2lvbnMiOlsiTUFOQUdFX09SREVSUyIsIk1BTkFHRV9DSEFOTkVMUyIsIk1BTkFHRV9PUkRFUlNfSU1QT1JUIiwiTUFOQUdFX1NFVFRJTkdTIiwiSEFORExFX1BBWU1FTlRTIiwiTUFOQUdFX1BMVUdJTlMiLCJIQU5ETEVfQ0hFQ0tPVVRTIiwiTUFOQUdFX0FQUFMiLCJNQU5BR0VfQ0hFQ0tPVVRTIiwiTUFOQUdFX1VTRVJTIiwiTUFOQUdFX09CU0VSVkFCSUxJVFkiLCJNQU5BR0VfUFJPRFVDVF9UWVBFU19BTkRfQVRUUklCVVRFUyIsIk1BTkFHRV9UQVhFUyIsIk1BTkFHRV9QQUdFUyIsIk1BTkFHRV9HSUZUX0NBUkQiLCJNQU5BR0VfTUVOVVMiLCJNQU5BR0VfU0hJUFBJTkciLCJJTVBFUlNPTkFURV9VU0VSIiwiTUFOQUdFX1NUQUZGIiwiTUFOQUdFX1BBR0VfVFlQRVNfQU5EX0FUVFJJQlVURVMiLCJNQU5BR0VfVFJBTlNMQVRJT05TIiwiTUFOQUdFX0RJU0NPVU5UUyIsIk1BTkFHRV9QUk9EVUNUUyIsIkhBTkRMRV9UQVhFUyJdfQ.EMiq1st7X_G_pvLI13_cTdgwPC7FK6rQ73KDMLl6AqHMNdgljQS7k44tW12EbcHLj8PMpBg56uwg9vHmJicU2reS9AzZdmZiWS5I-bobuliBQ7zcCK0AGnNo5SlPBrRojIT_a3SNebElcZFyjmDDuQWmsZdbgtq-SYi1NqC4DntRrx7uPPhwLQaGflREiX8iSThFaH7sxnWEex2c8BnTjdPY5ikJkNLJDJdHuPMDlw-DL1Pt1-XRFTUPNL4pjkCJKGxRgsD03MG81indgs61yuFKZvQOPXtceOYRHE3xla86vtSOV_V8FRRpxTa1kAh3jTHA2hj4IRDGd9Ksb21GPA' \
  -H 'content-type: application/json' \
  -H 'origin: https://taxes.staging.saleor.app' \
  -H 'referer: https://taxes.staging.saleor.app/providers/taxjar/3c804a25-3f02-4b84-aa38-a4db8d3cfdb7' \
  -H 'saleor-api-url: https://master.staging.saleor.cloud/graphql/' \
  -H 'sec-ch-ua: "Not.A/Brand";v="8", "Chromium";v="114", "Google Chrome";v="114"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36' \
  --data-raw '{"0":{"value":{"name":"taxjar2","isSandbox":false,"address":{"country":"US","zip":"92614","state":"CA","city":"Irvine","street":"2000 Main street"}},"id":"3c804a25-3f02-4b84-aa38-a4db8d3cfdb7"}}' \
  --compressed`
![Screenshot 2023-06-15 at 14 53 50](https://github.com/saleor/apps/assets/24992893/2565f75a-8b19-41ae-9d86-53af6ec0638d)


https://github.com/saleor/apps/assets/24992893/0aa8105a-51ca-4aa6-8217-0d997a6651bf

**Comment by yellowee** [comment]
When there is only one provider and a channel has `Use tax app `selected as the tax calculation method, it is not populated on the app settings and on a new order:
https://master.staging.saleor.cloud/dashboard/orders/T3JkZXI6OTZhZWJiYTAtMGE0My00NjljLTkwMjQtOWI1OWM3ODZiNzg3
![Screenshot 2023-06-15 at 15 39 26](https://github.com/saleor/apps/assets/24992893/1ed32bce-c184-49be-a61e-5b39eeaa17ba)
![Screenshot 2023-06-15 at 15 42 42](https://github.com/saleor/apps/assets/24992893/ade4f5f9-6538-4f24-b2d5-8cdceadc6cc9)
![Screenshot 2023-06-15 at 15 38 11](https://github.com/saleor/apps/assets/24992893/9474294d-a2ef-4560-81e5-ad47ee5c9ed2)

**Comment by yellowee** [comment]
Fetching provider's config returns 500 when no providers are added:
`curl 'https://taxes.staging.saleor.app/api/trpc/providersConfiguration.getAll,channelsConfiguration.fetch?batch=1&input=%7B%7D' \
  -H 'authority: taxes.staging.saleor.app' \
  -H 'accept: */*' \
  -H 'accept-language: en-GB,en;q=0.9' \
  -H 'authorization-bearer: eyJhbGciOiJSUzI1NiIsImtpZCI6IjEiLCJ0eXAiOiJKV1QifQ.eyJpYXQiOjE2ODY4MzgxNTgsIm93bmVyIjoic2FsZW9yIiwiaXNzIjoiaHR0cHM6Ly9tYXN0ZXIuc3RhZ2luZy5zYWxlb3IuY2xvdWQvZ3JhcGhxbC8iLCJleHAiOjE2ODY5MjQ1NTgsInRva2VuIjoiTTJpckZtelZBU1IzIiwiZW1haWwiOiJ0ZXN0ZXJzK2Rhc2hib2FyZEBzYWxlb3IuaW8iLCJ0eXBlIjoidGhpcmRwYXJ0eSIsInVzZXJfaWQiOiJWWE5sY2pveE1ETXoiLCJpc19zdGFmZiI6dHJ1ZSwiYXBwIjoiUVhCd09qZzQiLCJwZXJtaXNzaW9ucyI6WyJIQU5ETEVfVEFYRVMiLCJNQU5BR0VfT1JERVJTIl0sInVzZXJfcGVybWlzc2lvbnMiOlsiTUFOQUdFX09SREVSUyIsIk1BTkFHRV9DSEFOTkVMUyIsIk1BTkFHRV9PUkRFUlNfSU1QT1JUIiwiTUFOQUdFX1NFVFRJTkdTIiwiSEFORExFX1BBWU1FTlRTIiwiTUFOQUdFX1BMVUdJTlMiLCJIQU5ETEVfQ0hFQ0tPVVRTIiwiTUFOQUdFX0FQUFMiLCJNQU5BR0VfQ0hFQ0tPVVRTIiwiTUFOQUdFX1VTRVJTIiwiTUFOQUdFX09CU0VSVkFCSUxJVFkiLCJNQU5BR0VfUFJPRFVDVF9UWVBFU19BTkRfQVRUUklCVVRFUyIsIk1BTkFHRV9UQVhFUyIsIk1BTkFHRV9QQUdFUyIsIk1BTkFHRV9HSUZUX0NBUkQiLCJNQU5BR0VfTUVOVVMiLCJNQU5BR0VfU0hJUFBJTkciLCJJTVBFUlNPTkFURV9VU0VSIiwiTUFOQUdFX1NUQUZGIiwiTUFOQUdFX1BBR0VfVFlQRVNfQU5EX0FUVFJJQlVURVMiLCJNQU5BR0VfVFJBTlNMQVRJT05TIiwiTUFOQUdFX0RJU0NPVU5UUyIsIk1BTkFHRV9QUk9EVUNUUyIsIkhBTkRMRV9UQVhFUyJdfQ.hDn0F5iG58GoJj-ugrg6BKEbjP9qf0dnUTSh8XsaZx2D-ylbV0GZAvFeR0btZp5QKtiusZOeqbWYPi8_CTBSMTFmzlzz0w-NWRj3jrbql4SiqXlekP0gLfd4UBht33AV_3PY5sR3xeQGmQre6r1LHWjGzLZjfwiXIP5Ex-ga_z2EyOoFW8g_xPTfA-BDBeJQfI8-XfxQYSVjPNbcpFj783EbrsGrv4oVXD-XYSk7rQCuVLWtzgPk8Zc4TGZGs1bXhNd9F--yyf-gwLAUxjeE8tXSRwM5b3_OmwoOwy2GanZ7RNNupAiWtuU58fOWepctJEU_POaMHeuSN_trIWIUAg' \
  -H 'content-type: application/json' \
  -H 'referer: https://taxes.staging.saleor.app/configuration' \
  -H 'saleor-api-url: https://master.staging.saleor.cloud/graphql/' \
  -H 'sec-ch-ua: "Not.A/Brand";v="8", "Chromium";v="114", "Google Chrome";v="114"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36' \
  --compressed`
![Screenshot 2023-06-15 at 16 07 37](https://github.com/saleor/apps/assets/24992893/280cec5e-cfef-4b7f-83ea-bcc6cae8e2f4)

**Comment by yellowee** [comment]
1. Install tax app.
2. Add TaxJar provider.
3. Update channel to use tax strategy tax_app.
4. Update tax app to use TaxJar on this channel.
5. Create a new order in the channel and assign the existing customer and add a new valid address.
6. Select a shipping method.
7. Run query for check app wehbook eventDeliveries:

Actual result: Calculation of taxes fails.
```
(...)
                       {
                                "node": {
                                    "status": "FAILED",
                                    "eventType": "ORDER_CALCULATE_TAXES",
                                    "createdAt": "2023-06-15T14:15:53.757459+00:00",
                                    "attempts": {
                                        "edges": [
                                            {
                                                "node": {
                                                    "duration": 0.415892,
                                                    "status": "FAILED",
                                                    "response": "{\"error\":\"No address found in taxBase\"}",
                                                    "responseStatusCode": 500,
                                                    "responseHeaders": "{\"Cache-Control\": \"public, max-age=0, must-revalidate\", \"Connection\": \"keep-alive\", \"Content-Length\": \"39\", \"Content-Type\": \"application/json; charset=utf-8\", \"Date\": \"Thu, 15 Jun 2023 14:15:54 GMT\", \"Etag\": \"\\\"cb0evh9jbp13\\\"\", \"Server\": \"Vercel\", \"Strict-Transport-Security\": \"max-age=63072000\", \"X-Matched-Path\": \"/api/webhooks/order-calculate-taxes\", \"X-Vercel-Cache\": \"MISS\", \"X-Vercel-Id\": \"iad1::iad1::rppgj-1686838553868-252b1009004a\"}",
                                                    "requestHeaders": "{\"Content-Type\": \"application/json\", \"X-Saleor-Event\": \"order_calculate_taxes\", \"X-Saleor-Domain\": \"master.staging.saleor.cloud\", \"X-Saleor-Signature\": \"eyJhbGciOiJSUzI1NiIsImI2NCI6ZmFsc2UsImlzcyI6Imh0dHBzOi8vbWFzdGVyLnN0YWdpbmcuc2FsZW9yLmNsb3VkL2dyYXBocWwvIiwia2lkIjoiMSIsInR5cCI6IkpXVCJ9..mtpOhYs9RAn2R92FvQDVO53rCeW8YQXJoJmRPVgfhoDKSCd9ppteF2mYi3PUbb_4n82bVJCKYzK6TsEbj57-bim5RiOxVOVg15Q1hF1o0fa6gEeEdI71tSOMOMdb6I4eX14hb3yQjWJCG1a0VzBUlRbhcQssrm474Fwsa3QWmIT3Pvj4wyzPySjrOTQ3s9NX-XUu_egmqGoOctsm-b3ZyzBekA60NYVnu1HThi8eLYF9IJxbbdx1W9F08neL-3IeIymZzSni-Wd_IGHB7bXnsAjxy7UYOwg039Omq6u7ST95xYlSTwSPVHMUyfVGtf7O92Eq1JR-WOMP-TvRJ9EOPg\", \"Saleor-Event\": \"order_calculate_taxes\", \"Saleor-Domain\": \"master.staging.saleor.cloud\", \"Saleor-Signature\": \"eyJhbGciOiJSUzI1NiIsImI2NCI6ZmFsc2UsImlzcyI6Imh0dHBzOi8vbWFzdGVyLnN0YWdpbmcuc2FsZW9yLmNsb3VkL2dyYXBocWwvIiwia2lkIjoiMSIsInR5cCI6IkpXVCJ9..mtpOhYs9RAn2R92FvQDVO53rCeW8YQXJoJmRPVgfhoDKSCd9ppteF2mYi3PUbb_4n82bVJCKYzK6TsEbj57-bim5RiOxVOVg15Q1hF1o0fa6gEeEdI71tSOMOMdb6I4eX14hb3yQjWJCG1a0VzBUlRbhcQssrm474Fwsa3QWmIT3Pvj4wyzPySjrOTQ3s9NX-XUu_egmqGoOctsm-b3ZyzBekA60NYVnu1HThi8eLYF9IJxbbdx1W9F08neL-3IeIymZzSni-Wd_IGHB7bXnsAjxy7UYOwg039Omq6u7ST95xYlSTwSPVHMUyfVGtf7O92Eq1JR-WOMP-TvRJ9EOPg\", \"Saleor-Api-Url\": \"https://master.staging.saleor.cloud/graphql/\"}"
                                                }
                                            }
                                        ]
                                    },
                                    "payload": "{\"__typename\": \"CalculateTaxes\", \"taxBase\": {\"pricesEnteredWithTax\": true, \"currency\": \"GBP\", \"channel\": {\"slug\": \"re\"}, \"discounts\": [], \"address\": null, \"shippingPrice\": {\"amount\": 0.0}, \"lines\": [], \"sourceObject\": {\"user\": null}}, \"recipient\": {\"privateMetadata\": [{\"key\": \"channel-configuration__https://master.staging.saleor.cloud/graphql/\", \"value\": \"09477931722d52b962aea0d23174e59030ab51c397dba65500dbc51df29205e711649b1577e78b2ebf474fe23aa954d394cb4b33513d79d82d4863ef10219957511bbd9920b3583505b6749f9c8c10dd99b9112305d20cf92f6de48fb5f065982f9d49f83ff9a0f9e84e31422e87a5ef90d6af0fc3b4fa9194b867e00a12aa8aae5358e06248d713\"}, {\"key\": \"tax-providers-v2__https://master.staging.saleor.cloud/graphql/\", \"value\": \"ca544c50eb31261274ed08e52f2116de56bdbe9cc3a885cf6dc0f2e69900e1fefb6f22b7055ee96a857ce0c5e7dceb5aec9ab973e1cec46b874a13dfb212e6c6485cd58261d4401c92e1d811d602efa83666a0b06f93f9024d2c439e348ff4c213b96de16ab3842822d0b3a025b6a43330923480692731d519e811c0b6b264fb67c467885472fa4dad07ad1dc1b1f8e4d361b0dc4c40b3e31d2db318025e56f71fe779778a8f768658024d99b4e98e59671031ff5f832544ac03bc21d1a675ff605d344da5bdcb4ffafd0b9dbbe9f3036a6e8c72d060e09d5a6fea0f853d12ae297a85f6db36dfe7501d6a1aa527a2e8e20e37345243b634d9c69832688425b63d5ef4cb1ca3ce1f7a55fe885b8bfb8b66e79ca9930711320eb6f85edc1eaaf9601ea24225182c0a\"}]}}"
                                }
                            }
                        ]
                    },
                    "__typename": "Webhook"
                },
```
App id: "QXBwOjkx"

**Comment by yellowee** [comment]
1. Create Avatax provider with valid credentials.
2. Try to update Avatax provider by inputting **valid password _again_**.
Expected result: Update successful regardless of lack of changes.
Actual result: `Error: Invalid Avatax credentials.`
![Screenshot 2023-06-16 at 10 06 10](https://github.com/saleor/apps/assets/24992893/b93889a6-ffcf-4266-b021-73def739fcb5)

```
curl 'https://taxes.staging.saleor.app/api/trpc/avataxConnection.update?batch=1' \
  -H 'authority: taxes.staging.saleor.app' \
  -H 'accept: */*' \
  -H 'accept-language: en-GB,en;q=0.9' \
  -H 'authorization-bearer: eyJhbGciOiJSUzI1NiIsImtpZCI6IjEiLCJ0eXAiOiJKV1QifQ.eyJpYXQiOjE2ODY5MDIyMzcsIm93bmVyIjoic2FsZW9yIiwiaXNzIjoiaHR0cHM6Ly9tYXN0ZXIuc3RhZ2luZy5zYWxlb3IuY2xvdWQvZ3JhcGhxbC8iLCJleHAiOjE2ODY5ODg2MzcsInRva2VuIjoiTTJpckZtelZBU1IzIiwiZW1haWwiOiJ0ZXN0ZXJzK2Rhc2hib2FyZEBzYWxlb3IuaW8iLCJ0eXBlIjoidGhpcmRwYXJ0eSIsInVzZXJfaWQiOiJWWE5sY2pveE1ETXoiLCJpc19zdGFmZiI6dHJ1ZSwiYXBwIjoiUVhCd09qa3giLCJwZXJtaXNzaW9ucyI6WyJIQU5ETEVfVEFYRVMiLCJNQU5BR0VfT1JERVJTIl0sInVzZXJfcGVybWlzc2lvbnMiOlsiTUFOQUdFX1BMVUdJTlMiLCJNQU5BR0VfUFJPRFVDVFMiLCJNQU5BR0VfVEFYRVMiLCJNQU5BR0VfVVNFUlMiLCJNQU5BR0VfVFJBTlNMQVRJT05TIiwiTUFOQUdFX1NFVFRJTkdTIiwiTUFOQUdFX0RJU0NPVU5UUyIsIk1BTkFHRV9NRU5VUyIsIk1BTkFHRV9BUFBTIiwiSEFORExFX1BBWU1FTlRTIiwiTUFOQUdFX0dJRlRfQ0FSRCIsIk1BTkFHRV9TVEFGRiIsIk1BTkFHRV9PUkRFUlMiLCJNQU5BR0VfUFJPRFVDVF9UWVBFU19BTkRfQVRUUklCVVRFUyIsIklNUEVSU09OQVRFX1VTRVIiLCJNQU5BR0VfU0hJUFBJTkciLCJIQU5ETEVfQ0hFQ0tPVVRTIiwiTUFOQUdFX0NIQU5ORUxTIiwiTUFOQUdFX09SREVSU19JTVBPUlQiLCJNQU5BR0VfUEFHRVMiLCJNQU5BR0VfQ0hFQ0tPVVRTIiwiSEFORExFX1RBWEVTIiwiTUFOQUdFX09CU0VSVkFCSUxJVFkiLCJNQU5BR0VfUEFHRV9UWVBFU19BTkRfQVRUUklCVVRFUyJdfQ.hDf17hUdSbkhEhEBad-UEeq4uMv20as0ngjxccjX5qy-OvSB6hgj4UffglKH330Aa6aw4HjjSjXCkSwfySmr6ubnvlvfprkpD7v-KlRNcWI43XJqrB9bMZZ1jkRfZLcW0ffYE-htLiJZFFwlC07DGpjfWred4BzcvoXUvPid7GRbbYmhS67HuykziwHMA0Zdh0sBhkWgOcfRofg4I-hTfjiWjKyIdM2-1zeJavQ_rUL1Cow9gl0T7pYfXp1CRrqHLFHJi5Ib6ykxoxqoymA_ld9arPWhj1JfsCXHJ3ZNP7KMk6rnISbcnxoj0YAQTNJcXDTjy70UPDS2yIex0dJr8g' \
  -H 'content-type: application/json' \
  -H 'origin: https://taxes.staging.saleor.app' \
  -H 'referer: https://taxes.staging.saleor.app/providers/avatax/3e54b690-e484-4c02-8c35-881386ee39ac' \
  -H 'saleor-api-url: https://master.staging.saleor.cloud/graphql/' \
  -H 'sec-ch-ua: "Not.A/Brand";v="8", "Chromium";v="114", "Google Chrome";v="114"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36' \
  --data-raw '{"0":{"value":{"name":"ava","isSandbox":true,"companyCode":"","isAutocommit":false,"shippingTaxCode":"","address":{"country":"US","zip":"92614","state":"California","city":"Irvine","street":"2000 Main St"},"credentials":{"password":"F443668981A3CD0A"}},"id":"3e54b690-e484-4c02-8c35-881386ee39ac"}}' \
  --compressed
```

**Comment by peelar** [comment]
> Please note: On UI it seems like a tax is calculated when Avatax is assigned Order #3244

@yellowee I suspect the case here is that the calculation failed when there was no address but succeeded once you provided the address. The webhook is triggered either way, and if we have no address, we just shoot an error right away.

**Comment by peelar** [comment]
@yellowee I marked the issues I fixed with 🚀 and things that you can ignore with 👍 (because they are either not a bug or the requirements have changed). 

Can you please revisit the 🚀 issues and confirm the bug is gone? 🙏

**Comment by yellowee** [comment]
@peelar When it comes to [this issue](https://github.com/saleor/apps/issues/554#issuecomment-1592986451) I confirm that there is now the possibility to create TaxJar provider with sandbox either disabled or enabled.
I've noticed another issue though:
I am able to create TaxJar provider with Live/Sandbox token regardless if the sandbox is disabled/enabled.
![Screenshot 2023-06-20 at 09 05 29](https://github.com/saleor/apps/assets/24992893/fb731bd1-296d-4eda-9df3-8439fc3e0eb3)

**Comment by yellowee** [comment]
[500 no providers](https://github.com/saleor/apps/issues/554#issuecomment-1593145771) - fixed ✅ 
[Unable to update a provider](https://github.com/saleor/apps/issues/554#issuecomment-1592998539) - fixed ✅ 
[500 updating Avatax with the same password](https://github.com/saleor/apps/issues/554#issuecomment-1594289043) - I was able to reproduce it ❌

**Comment by peelar** [comment]
> https://github.com/saleor/apps/issues/554#issuecomment-1594289043 - I was able to reproduce it ❌

Please confirm:
1. Create avatax provider
2. Go to edit
3. Delete all the characters. Fill with the valid credentials again
4. Save
5. Get an error

If that's correct, can you please record a video? 🙏 because I didn't manage to reproduce

**Comment by yellowee** [comment]
@peelar Here is the screen recording:

https://github.com/saleor/apps/assets/24992893/aa2bc2ed-17b6-4473-a198-51285ba8f3d5

Please note: Upon updating I still had valid Avalara password in my clipboard.

**Comment by peelar** [comment]
@yellowee can you please check again?

**Comment by yellowee** [comment]
https://github.com/saleor/apps/issues/554#issuecomment-1594289043 - fixed ✅ 

@peelar There is a new console error though returned on app config page - regardless if a provider is added or not:
``` Error: Abort fetching component for route: "/configuration" ```
<img width="1376" alt="Screenshot 2023-06-21 at 07 47 14" src="https://github.com/saleor/apps/assets/24992893/d6d5c772-de21-400f-af44-ead5786a2323">
