### ISSUE TITLE
Klaviyo Unable to modify data fields for installation

### ISSUE THREAD

**Issue by Colophon-Foundry** [saleor/apps#653]
I've tried to connect Klaviyo via our dev environment, and it looks like it has installed. I've added in the Private API (from Klaviyo) into the Public Key field, however it is now saying the App doesn't have an access token, and I am unable to get back to the page that allows me to change the values?

Steps Taken
- Install Klaviyo through the app page

- Go to settings and input the Private API key (under PUBLIC KEY)*
- Hit Save
- Try and access Klaviyo, and I get the error message listed below

<img width="486" alt="Screenshot 2023-06-16 at 15 03 59" src="https://github.com/saleor/apps/assets/32193288/a189859d-bdf4-414e-9328-011c00061a9c">

- Trying to adjust Settings I get the following page, with no way to amend my data input

<img width="782" alt="Screenshot 2023-06-16 at 15 04 22" src="https://github.com/saleor/apps/assets/32193288/1d240bcc-7553-4ceb-a69d-39292821bbf6">

*This was presumed as there is no PUBLIC KEY listed on Klaviyo's configuration

**Comment by lkostrowski** [comment]
Hey, can you please provide you Dashboard version?

**Comment by Colophon-Foundry** [comment]
dashboard `v3.12.14`
core `v3.12.26`

**Comment by lkostrowski** [comment]
I tried Klaviyo on 3.12.14 and I couldn't reproduce the problem...

Let me confirm - are you opening the app correctly?

There are 2 clickable areas in the dashboard - the row opens the app, the "Settings" button opens "manage app" screen. Looks like you opened the latter?

<img width="906" alt="Zrzut ekranu 2023-06-19 o 10 34 59" src="https://github.com/saleor/apps/assets/9268745/1a374356-aa2a-4f2a-8267-fa277a428205">


I know this UI is confusing and we have changed it in latest Saleor release

**Comment by Colophon-Foundry** [comment]
First clickable area gives the error message and clicking settings gives the second About this app screen

**Comment by lkostrowski** [comment]
@Colophon-Foundry have you tried to reinstall the app?

If it still doesn't work, we need to debug it further:

1. Open https://klaviyo.saleor.app/configuration
2. Open devtools > console
3. Paste `window.localStorage.debug='app-sdk:*'`
4. Open dashboard again
5. Open app (row click)
6. Open devtools -> console, ensure "all levels" are set 
7. Paste results - ensure tokens are redacted

**Comment by lkostrowski** [comment]
As discussed, please clear your browser session and local storage, looks like something was cached
