### ISSUE TITLE
QA: Tax Code matcher

### ISSUE THREAD

**Issue by peelar** [saleor/apps#665]
# QA: Tax Code matcher

## Context

We added a crucial feature to the Taxes App: tax code matcher. Here is an overview of what it does:

In Saleor, we have a feature called Tax Classes. They allow you to declare an override for a product's base tax rate. This comes in handy when you have a group of products that you know have their individual tax rate (e.g., alcohol).

For tax classes to affect the tax providers in the Taxes App, they must be mapped to the tax codes that these providers expect.

Let's say we are using Avatax. Beer in Avatax has a tax code of "PA2010200". If we have a "beer" tax class in Saleor, we must map it to the "beer" tax code in Avatax. This way, once the tax calculation for an order containing beer is triggered, the Taxes App will know to assign the order line the "beer" Avatax tax code.

Tax Code Matcher is a functionality that allows for linking the Saleor tax class with the provider's tax code.

## Scenarios

**1. Tax Code matcher view displays when created at least one provider**

By default, Tax Code Matcher view is hidden. After you create at least one provider, it should show as the third section on the home screen:

<img width="1207" alt="image" src="https://github.com/saleor/apps/assets/44495184/50b89634-1cb3-4606-be65-99e264c0e30e">

When created at least one configuration for Avatax, and one for TaxJar, you should see entries in the table for both.

Clicking on "Configure" should redirect you to the tax code matcher.

**2. Each tax code matcher (there are two, one for Avatax, one for TaxJar) should render a list tax classes and tax codes**

In the tax code matcher view, you should see a column of Saleor tax classes and a column of selects with provider tax codes as options.

The user should be able to assign/unassign a tax code.

**3. Matched tax codes should reflect in the transactions in the provider**

1. Set a tax class on a product
2. Match tax class to a provider tax code
3. Create an order with the product

The following should result in creating a transaction (e.g. in Avatax) with the correct tax code (the one you mapped to).

**4. When no tax code matches, the tax calculation should succeed anyway**

1. Don't create any matches in the tax code matcher
2. Create an order using the provider

The following should result in returning taxes/creating a transaction without any tax code.

**Comment by yellowee** [comment]
Unable to fetch Avatax tax codes:
1. Create Taxes app.
2. Create Avatax provider.
3. Go to Tax code matcher config page for Avatax.
Expected: User is able to select tax codes for each element on the list.
Actual: 
Avatax tax codes load for few seconds and then Not assigned option appears in every dropdown.

```GET https://taxes.staging.saleor.app/api/trpc/avataxTaxCodes.getAllForId?batch=1&input=%7B%220%22%3A%7B%22connectionId%22%3A%22a455ae38-57d4-42ee-945f-a6e3898162d6%22%7D%7D 500```
![Screenshot 2023-06-21 at 12 36 19](https://github.com/saleor/apps/assets/24992893/fda01358-adcc-4279-9625-7613ed9c458e)
https://github.com/saleor/apps/assets/24992893/f2668bb6-0e2b-4ef6-8c28-b0c5db78e6d3

Please note: The issue does not occur on TaxJar provider.

**Comment by yellowee** [comment]
Question: Should Tax code matcher configuration be available for a provider type (Avatax/TaxJar) or should there be as many configurations as many providers are created?
![Screenshot 2023-06-21 at 12 53 00](https://github.com/saleor/apps/assets/24992893/ed0bd2c7-5706-47be-b7f5-e8a681990199)

**Comment by yellowee** [comment]
No taxes are calculated when no tax code is provided:

1. Create Taxes app.
2. Setup channel to using tax app.
3. Create a provider.
4. Assign this provider to the afore mentioned channel.
5. Don't create any matches in the tax code matcher.
6. Create an order on the channel.

Expected: Taxes are calculated in totals.
Actual: No tax is calculated for the order, eg. Order #3232 (TaxJar), Order #3233 (Avatax)
![Screenshot 2023-06-21 at 13 14 33](https://github.com/saleor/apps/assets/24992893/1397c77f-e550-44d4-8cd6-9dd5a23c40cc)

**Comment by lkostrowski** [comment]
@yellowee there is a single config for taxes mapping per provider. So there is 0, 1 or 2. 

Provider configs share mapping so one Avatax mapping is shared by 2 avatax configs

**Comment by yellowee** [comment]
Tax not calculated for a transaction with a tax code provided:

1. Create Taxes app.
2. Setup USD channel to using tax app.
3. Create TaxJar provider.
4. Assign this provider to the afore mentioned channel.
5. Create a tax class and set it's tax to 50% for US.
6. In provider Tax code config select T-shirt tax code (53103000A0000 ) for this class.
7. Create an order with T-shirt on USD channel.
8. Create a transaction for this order.

Expected: 50% tax is applied on the order.
Actual: ``Taxes​does not apply``
![Screenshot 2023-06-22 at 08 28 28](https://github.com/saleor/apps/assets/24992893/84da0a3d-afc8-4511-b471-61f55d94dbec)
![Screenshot 2023-06-22 at 08 29 47](https://github.com/saleor/apps/assets/24992893/0715908a-3685-4b89-966b-300bdd296c93)
![Screenshot 2023-06-22 at 08 34 07](https://github.com/saleor/apps/assets/24992893/1e64eb0d-fca9-4fba-8bd6-8a5050bf0835)

Test order id: ``T3JkZXI6ZWNmNWQ4ODktN2M2NC00NjBhLTlmYmItY2IxNGYwMTk1MTA2``

I am unable to locate a response tax code field for any mutation or query related to this order - please advise, thanks.

**Comment by yellowee** [comment]
@peelar The tax has been applied in order id ``T3JkZXI6MTRjZDA3MmQtYmMyNy00ZDM5LWE2ZWUtM2NiMjFhMmUxMjIz`` when I provided the valid address for a customer ✅ 

The problem with transactions not showing up in TaxJar remains the same though:

![Screenshot 2023-06-28 at 09 16 13](https://github.com/saleor/apps/assets/24992893/91578fa2-8ced-4c70-b944-670805edfc4b)

Transaction id: ``VHJhbnNhY3Rpb25JdGVtOjQzYTcyYTE5LWQ1NDMtNDcxZC1hNjU2LTFhNjkwNGUxOGM2Zg==``

**Comment by peelar** [comment]
I created a separate issue for it: https://github.com/saleor/apps/issues/692

Closing this one for now. Thanks @yellowee 🙇
