### ISSUE TITLE
Install apps with Vercel or via CLI is not working

### ISSUE THREAD

**Issue by michalina-graczyk** [saleor/apps#69]
1. Create a new env
2. In apps install an app using 'Deploy to Vercel'
![image](https://user-images.githubusercontent.com/25908728/215432925-e19e9787-1cb6-4b11-b2c1-df6ff85ad78a.png)
3. Do all required steps in Vercel
4. Install app in dashboard
Current result: 
`"message":"Registration failed: could not save the auth data."`
`"message":"APL_NOT_CONFIGURED. App is configured properly. Check APL docs for help."` -> this one was for an app installed via CLI 

![image](https://user-images.githubusercontent.com/25908728/215432623-f24b8f4b-5516-423e-bf08-2e8dd3bcf591.png)

**Comment by lkostrowski** [comment]
We decided to drop "deploy to vercel" since its unstable and replace it with Github Fork

https://github.com/saleor/apps/issues/98

**Comment by simon-online** [comment]
This is the exact issue that I am getting when I try to install the CMS app that I have successfully deployed on Vercel at
https://saleor-apps-taupe.vercel.app/
 
![Screen Shot 2023-05-25 at 2 25 39 pm](https://github.com/saleor/apps/assets/10040020/07c3d913-f617-4f27-8118-0f58661e3ed2)

I tried this with
dashboard v3.13.3
core v3.13.16
apps v1.6.0

What can I do to resolve this?

**Comment by lkostrowski** [comment]
@simon-online you need to set up your APL layer 

https://docs.saleor.io/docs/3.x/developer/extending/apps/architecture/apl#what-is-apl

https://github.com/saleor/saleor-app-sdk/blob/main/docs/apl.md

On local development you can use FileAPL but in serverless environment you need to provide some layer of persistence. Can be redis/upstash/vercel KV etc

**Comment by simon-online** [comment]
Got it, thanks for that.

For anyone else interested I was able to deploy the cms app on Vercel by selecting [saleor/apps](https://github.com/saleor/apps) as an external repository for a new Vercel project which automatically forked it on GitHub.

For successful deployment I did the following things:

- Under project Storage I created a KV database and connected it to the environments I was deploying for. This will automatically add some new KV_* environment variables to your project with the KV database connection details.
- Under project Settings > Environment Variables I added the following new environment variables:
- `APL` = `upstash`
- `UPSTASH_URL` = to the same value copied from `KV_REST_API_URL`
- `UPSTASH_TOKEN` = to the same value copied from `KV_REST_API_TOKEN`
- Under project Settings > General set the Root Directory to `apps/cms` or whatever app you want to deploy as each app directory is a separate Next JS project.

This would also be the same way that you could deploy your own custom Saleor apps on Vercel.

**Comment by lkostrowski** [comment]
Great @simon-online , good to know that our native Upstash APL works with the same values as Vercel KV 🚀

**Comment by simon-online** [comment]
Although I seem to have hit another roadblock as detailed here:
https://github.com/saleor/apps/issues/513

Not sure if this is the result of trying to use the Upstash APL with Vercel KV.
