### ISSUE TITLE
Allow registerHandler to inject hooks with custom logic

### ISSUE THREAD

**Issue by lkostrowski** [saleor/apps#73]
examples - like onStart, onAuthenticated 

Allow to e.g. bootstrap app (set default config) on app installation

**Comment by krzysztofwolski** [comment]
One of the things I liked in the webhooks handler factory is the exposed `context` and our handler factory should prepare it as well:
- preRegister callback should expose with Saleor API URL (for example validate if that's a request from the right domain)  
- postRegister - should add context with complete AuthData

To be considered:
What should we return, if the App registered and postRegister fails?
