### ISSUE TITLE
Duplicated message delivery

### ISSUE THREAD

**Issue by krzysztofwolski** [saleor/apps#746]
Some messages are sent multiple times when using the SMTP provider

**Comment by krzysztofwolski** [comment]
Found the issue - multiple app installations.

How to reproduce:
- install EAM app
- configure provider and event
- install the app again, configure

How it should behave:
- the old webhook should be rejected, since the app id is different
- the new webhook should be handled, because it's current app installation

How it behaves:
- the old webhook is **not** rejected since ID is not checked
- both webhooks looks for the active configuration and send the messages

How can we fix it:
- webhook handler should check the id - the problem is I haven't found it in the headers nor checksum, probably we would need to take it from the recipient
- Implement per configuration hooks: #725

**Comment by lkostrowski** [comment]
This is not a bug. I believe in production setup no one will install >1 app like we are on the development.

Also eventually we will block multiple installations
