### ISSUE TITLE
Algolia / search app: Variant metadata not synced

### ISSUE THREAD

**Issue by JannikZed** [saleor/apps#774]
In Algolia I see the property "metadata", that is empty for all of our products / product variants: 
<img width="1086" alt="Screenshot 2023-07-17 at 10 41 07" src="https://github.com/saleor/apps/assets/7526174/ef6397ac-ddc0-4a46-b9c4-1c9ead02c42e">

When I add metadata to a product variant (not the product itself), I would assume, that the field gets updated in Algolia as well: 
<img width="1015" alt="Screenshot 2023-07-17 at 10 42 03" src="https://github.com/saleor/apps/assets/7526174/bf715e6a-d8c2-470f-b4f7-7c4b6caecc2e">

But it's not happening - it seems like only the product metadata gets synced and not the product variant metadata. 
Is that by design? Our use case is: product ratings. We are synchronizing customer product ratings from review.io to the product variant metadata and need this data in algolia, too.

**Comment by lkostrowski** [comment]
Hey, I think it should be added. We will look into that
