### ISSUE TITLE
Algolia/ search app: how to know, if product has multiple variants?

### ISSUE THREAD

**Issue by JannikZed** [saleor/apps#775]
We are using the disting feature from Algolia, as described by your app. This works as expected - when asking Algolia to return us all products in a specific category, we just get one hit per product, no matter how many variants this product has. 
One problem that we have now: how to know, if the result is a single variant product or multi-variant? We need this information, to render different information in the product overview page: 
- for single variant product: show add to cart button
- for multi-variant product: show button "select options"

is there a way to do that now? Otherwise, I would recommend to add a generic "variants" array to every item (just with the id, or id and name)
```
"variants": [
        {
          "id": "UHJvZHVjdFZhcmlhbnQ6NTk1OA=="
        },
        {
          "id": "UHJvZHVjdFZhcmlhbnQ6NTk1OQ=="
        },
        {
          "id": "UHJvZHVjdFZhcmlhbnQ6NTk2MA=="
        },
        {
          "id": "UHJvZHVjdFZhcmlhbnQ6NTk2MQ=="
        },
        {
          "id": "UHJvZHVjdFZhcmlhbnQ6NTk1Nw=="
        },
        {
          "id": "UHJvZHVjdFZhcmlhbnQ6NTk2Mg=="
        },
        {
          "id": "UHJvZHVjdFZhcmlhbnQ6NTk2Mw=="
        }
      ]
```
this is very important to us now.

**Comment by lkostrowski** [comment]
Hey

I've checked quickly how it works. App is indexing variants, not products, so every time you get a result, its a variant. Variant do not have a reference to other variants, but it does have a reference to the product (`productId` attribute).

I'm not not algolia expert by maybe you can look into grouping and try to group them by parent product ID? 
https://www.algolia.com/doc/guides/managing-results/refine-results/grouping/

We can look into adding needed attributes to the products - we actually want to add more of them and allow to configure which attributes are saved - but we can start looking into that earliest next week

BTW I'm not sure if you should rely on Algolia results to render your PDP. 
If you call Saleor directly, you can have all the data you need and its very reliable. If you use algolia, you have 2 more possible points of failure (app and Algolia itself)
