### ISSUE TITLE
Research: Update Algilia index on stock changes

### ISSUE THREAD

**Issue by krzysztofwolski** [saleor/apps#836]
Related webhooks:
PRODUCT_VARIANT_OUT_OF_STOCK
PRODUCT_VARIANT_BACK_IN_STOCK
PRODUCT_VARIANT_STOCK_UPDATED

Using OUT_OF / BACK_IN events will be a more performance friend solution. Most of usecases depend on "in stock" flag rather than the exact stock value.

**Comment by JannikZed** [comment]
I also think, that for most cases, the out of stock and back in stock should be sufficient. I just had one other use case: rendering the information "low stock" on the category pages for example. So it would be nice, of the total stock is below the "Checkout limits" or not. Is there already some logic in Saleor handling the low stock scenario?
<img width="400" alt="Screenshot 2023-08-07 at 18 13 28" src="https://github.com/saleor/apps/assets/7526174/ed435b1c-132d-43a0-a74d-e80efe7703d8">

**Comment by lkostrowski** [comment]
@JannikZed I dont think we have (and want to) implement a "low stock". It is very "business specific" what a low stock is.

You can build an integration that will listen on stock changes and update your product with proper attributes or metadata, eg:
1. Listen on stock changes
2. Verify if "low stock" condition is met
3. Set a metadata on the product

With metadata you can enrich your product with any information you need.

Regarding original issue, we haven't yet discussed if this is something we will add to Algolia. Product pages should be rendered with data from Saleor. We need to evaluate which fields should be added to the search engine

**Comment by JannikZed** [comment]
@krzysztofwolski concerning the general discussion: we need all fields, that are important for shop facets to be located in Algolia, as these parts of the page are created with algolia / search data. We want to have facets for "user review start count", "price ranges", "categories", "availability". Just as a feedback on that. These are the most important fields for us.

**Comment by lkostrowski** [comment]
@JannikZed let us refine this - you can track everything here https://github.com/saleor/apps/issues/825

**Comment by krzysztofwolski** [comment]
The "inStock" flag has been added (#874) and released in the latest version.
As discussed earlier, keeping the exact stocks in the Algolia would generate a lot of additional synchronization traffic and can be implemented on the frontend side, using Saleor API and custom logic tailored to the business needs.
