### ISSUE TITLE
Search app - Algolia initial products indexing fails with "Record at the position * is too big" error

### ISSUE THREAD

**Issue by pitkes22** [saleor/apps#926]
I am trying to use the latest version of the Search App, after I set up the Algolia integration I tried to run initial products indexing. After the products were loaded from the Saleor, the import to Algolia failed with the following  error:

```json
{
    "message": "Record at the position 76 objectID=UHJvZHVjdDo1MDU=_UHJvZHVjdFZhcmlhbnQ6Njgy is too big size=14072/10000 bytes. Please have a look at https://www.algolia.com/doc/guides/sending-and-managing-data/prepare-your-data/in-depth/index-and-records-size-and-usage-limitations/#record-size-limits",
    "position": 76,
    "objectID": "UHJvZHVjdDo1MDU=_UHJvZHVjdFZhcmlhbnQ6Njgy",
    "status": 400
}
```

From the [Algolia documentation page mentioned in the error,](https://www.algolia.com/doc/guides/sending-and-managing-data/prepare-your-data/in-depth/index-and-records-size-and-usage-limitations/#record-size-limits) I understood that there is a [limit to the size of the single record](https://support.algolia.com/hc/en-us/articles/4406981897617-Is-there-a-size-limit-for-my-index-records-/). According to the current pricing, the limit is `10 KB` for the Free plan, and `Avg 10KB/Record max 100KB` for paid plans. I am not sure what `Avg 10KB` means there obviously needs to be a mechanism in this integration to limit the record size.

Also, From the UI perspective, there is no error visible, so without devtools it is hard to tell what happened.

![image](https://github.com/saleor/apps/assets/10003540/ae50f737-5df6-4bf0-b316-94d24802c5ba)

**Comment by lkostrowski** [comment]
Hey

We are aware of the problem #499 

We are going to implement a "picker" of what is synced to Algolia to avoid too large payloads.

Thanks for the report. Closing as a duplicate - you can subscribe on #499
